services:
  mongo:
    container_name: home-inventory-mongo
    image: mongo:7
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - home-inventory-network

  redis:
    container_name: home-inventory-redis
    image: redis:7-alpine
    restart: always
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis_data:/data
    networks:
      - home-inventory-network

  minio:
    container_name: home-inventory-minio
    image: minio/minio:latest
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
    ports:
      - ${S3_PORT}:9000
      - ${S3_CONSOLE_PORT}:9001
    volumes:
      - minio_data:/data
    networks:
      - home-inventory-network

volumes:
  mongo_data:
  redis_data:
  minio_data:

networks:
  home-inventory-network:
    driver: bridge
